### ISSUE TITLE
Failure building sourcekite on Debian 11 using Swift 5.5...

### ISSUE THREAD

**Issue by fphartnc** [vknabel/sourcekite#10]
I followed the directions (at https://marketplace.visualstudio.com/items?itemName=vknabel.vscode-swift-development-environment) for building and installing sourcekite from a git clone and got the attached build output.   I am running Debian 11 and I installed Swift 5.5 (Ubuntu 20.04 version).

Edit:  Initial post contained impression compiler had built a number of the downloaded git targets.  Not sure of that now, but I do know that the compiler works because I used it in REPL mode.  Is it possible there are some missing "include GLibc" directives?

Hoping to get sourcekite running so I can use Tensorflow items.

Any suggestions?
[skbldout.txt](https://github.com/vknabel/sourcekite/files/7307150/skbldout.txt)

**Comment by vknabel** [comment]
Hi @fphartnc, thanks for your feedback!
Does the branch [`fix/debian-5.5`](https://github.com/vknabel/sourcekite/tree/fix/debian-5.5) fix your issue?

**Comment by fphartnc** [comment]
Thanks for the quick action!  Looks like the compilation succeeded but writing the executable failed because of a permissions issue (see attachment)... I checked the permissions along the path and I (the user) have rwx the whole way.  Let me know if there's anything else you'd like me to check and/or post from the environment...
[skbld07out.txt](https://github.com/vknabel/sourcekite/files/7314440/skbld07out.txt)

**Comment by fphartnc** [comment]
BTW... I tried copying the file myself from the CLI and got the same message back, but was able to perform the copy as root (used the su command).  When looking at the contents of /usr/bin/local, I see everything else in there is owned by root... so you may need to precede that cp with a sudo...

**Comment by vknabel** [comment]
Thanks for testing!

When install fails, the Makefile will now retry cp with sudo. Released as 0.7.0.
Thanks!
