### ISSUE TITLE
Request textDocument/hover failed problem

### ISSUE THREAD

**Issue by gawainx** [vknabel/sourcekite#7]
It doesn't work for newest VS Code 1.34.0
VS Code VERSION: 1.34.0
Swift Version: 5.0
Xcode Version: 10.2.1

I install SDE and sourcekite as language server. When opening a swift project, the output told me that "Request textDocument/completion failed." or "Request textDocument/hover failed."

**Comment by vknabel** [comment]
Hi @gawainx, sorry for the late response!
Is the project you work in open source? In that case we could test everything in the same project.

---

Could you add the following snippet to your vscode settings (enables debug logging).
```
// .vscode/settings.json
{
  "sde.languageServerMode": "sourcekite",
  "sde.enableTracing.LSPServer": true,
  "sde.enableTracing.client": true
}
```

Thereafter restart your vscode window, reproduce your issue (e.g. hover over a variable) and paste all output of `Swift` into a new comment.

> **Note:** this leaks your current path and the source code of the current file. If your codebase is private ensure you test everything either on a new file or in a file which doesn't contain sensitive information.

**Comment by gawainx** [comment]
I just created[test project](https://github.com/gawainx/lsptest) and I pasted output to `report.txt` file.
I used [Tensorflow for swift toolchain](https://github.com/tensorflow/swift) as the xcode toolchain.

**Comment by vknabel** [comment]
Thank you very much for the great report and repo!

According to your log sourcekite itself cannot be started.
```
[sourcekite] ***stderr***dyld: Library not loaded: @rpath/libswiftCore.dylib
```

I guess this is related to the Tensorflow for Swift toolchain. Did you compile sourcekite with your Xcode toolchain and later switched to Tensorflow? If yes, a clean recompile after switching toolchains might help.

I will download and install Swift Tensorflow to validate basic functionality within the next few days.
