### ISSUE TITLE
make install 'XMLParser' is unavailable

### ISSUE THREAD

**Issue by bmaciag** [vknabel/sourcekite#8]
Error while make install:

'XMLParser' is unavailable: This type has moved to the FoundationXML module. Import that module to use it.

**Comment by vknabel** [comment]
Hi @bmaciag.
Which Swift version do you use? (`swift --version`)
What is your operating system?
Could you additionally append all logs from `make install`?

**Comment by mschrettenbrunner** [comment]
Hi @vknabel,

same situation with Swift 5.1 (release) and snapshot on Ubuntu 18.04.3

**Comment by vknabel** [comment]
Hi @mschrettenbrunner!

Can you run the following commands and just paste the output in here?


```bash
$ git rev-parse --short HEAD
$ swift -version
$ swift package clean
$ make install # optionally: PREFIX=/usr/local
```

**Comment by mschrettenbrunner** [comment]
Hi @vknabel, 

Thanks for your fast reply .. Meanwhile I run/ test S4TF (5.1-dev (LLVM c5340df2d1, Swift 0a4018fd06) with Apples sourcekit-lsp on vscode (v1.38.1 and 1.39.0).

**Comment by dbonner** [comment]
This is how I fixed this problem:
After receiving this error during make install:
sudo nano ~/sourcekite/.build/checkouts/SWXMLHash/Source/SWXMLHash.swift
Add:
import FoundationXML
Replace
Foundation.XMLParser
with
FoundationXML.XMLParser
You need to replace it about 28 times.
Then run:
make install
and it works.
I think you need to update your dependancies to use the latest version of SourceKitten (0.27.0) which will in turn build with the latest version SWXMLHash.swift (which does not contain this error).  See my comment on the SWXMLHash comments page which is pasted below:
"Apologies.  I just realised that you have updated SWXMLHash to import FoundationXML.  I was building sourcekite (https://github.com/vknabel/sourcekite), which in turn is dependant on SourceKitten (https://github.com/jpsim/SourceKitten, .package(url: "https://github.com/jpsim/SourceKitten", from: "0.24.0"),), which in turn is dependant on SWXMLHash (.package(url: "https://github.com/drmohundro/SWXMLHash.git", .upToNextMinor(from: "4.9.0")).  The version of the file SWXMLHash.swift that gets downloaded when I build sourcekite does not account for the change to needing the FoundationXML module.   I'll go back to the sourcekite developer and ask her to update her dependancies.  Hopefully that will fix things."

**Comment by sideef5ect** [comment]
@dbonner thanks you for your advise
and if you use vim, it will be more easier

sudo vim ~/sourcekite/.build/checkouts/SWXMLHash/Source/SWXMLHash.swift

Add:
import FoundationXML

in command mode, type:
:%s/Foundation.XMLParser/FoundationXML.XMLParser/g

**Comment by vknabel** [comment]
Thanks for your help. As according to https://github.com/drmohundro/SWXMLHash/issues/229 has already been fixed, I bumped the SourceKitten dependency.

Can you confirm [0.6.1](https://github.com/vknabel/sourcekite/releases/tag/0.6.1) fixes your issue?

**Comment by dbonner** [comment]
Hi @vknabel and thanks for the advice about vim @KnaveM,
Yes, I can confirm that 0.6.1 fixes this issue and sourcekite is built successfully.
There is a warning message (see below for the output of the build process with warning message at the bottom).  I don't know if this warning message is a concern:
```bash
git clone https://github.com/vknabel/sourcekite
cd sourcekite
mkdir /home/daniel/usr/local/bin
make install PREFIX=/home/daniel/usr/local
```
Output:

```bash
swift build -c release
Fetching https://github.com/Quick/Nimble.git
Fetching https://github.com/Carthage/Commandant.git
Fetching https://github.com/mattgallagher/CwlPreconditionTesting.git
Fetching https://github.com/jpsim/Yams.git
Fetching https://github.com/mattgallagher/CwlCatchException.git
Fetching https://github.com/Quick/Quick.git
Fetching https://github.com/jpsim/SourceKitten
Fetching https://github.com/drmohundro/SWXMLHash.git
Cloning https://github.com/Quick/Nimble.git
Resolving https://github.com/Quick/Nimble.git at 8.0.4
Cloning https://github.com/drmohundro/SWXMLHash.git
Resolving https://github.com/drmohundro/SWXMLHash.git at 5.0.1
Cloning https://github.com/jpsim/Yams.git
Resolving https://github.com/jpsim/Yams.git at 2.0.0
Cloning https://github.com/mattgallagher/CwlPreconditionTesting.git
Resolving https://github.com/mattgallagher/CwlPreconditionTesting.git at 1.2.0
Cloning https://github.com/jpsim/SourceKitten
Resolving https://github.com/jpsim/SourceKitten at 0.27.0
Cloning https://github.com/Carthage/Commandant.git
Resolving https://github.com/Carthage/Commandant.git at 0.17.0
Cloning https://github.com/mattgallagher/CwlCatchException.git
Resolving https://github.com/mattgallagher/CwlCatchException.git at 1.2.0
Cloning https://github.com/Quick/Quick.git
Resolving https://github.com/Quick/Quick.git at 2.2.0
/home/daniel/sourcekite/.build/checkouts/SourceKitten/Source/SourceKittenFramework/CodeCompletionItem.swift:65:65: warning: cast from 'SourceKitRepresentable?' to unrelated type 'CodeCompletionItem.NumBytesInt' (aka 'Int') always fails
                numBytesToErase: dict["key.num_bytes_to_erase"] as? NumBytesInt)
                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^   ~~~~~~~~~~~
[13/13] Linking sourcekite
cp .build/release/sourcekite /home/daniel/usr/local/bin/
```

All the best,
Dan
