### ISSUE TITLE
sourcekite mostly does not work on macOS

### ISSUE THREAD

**Issue by dbonner** [vknabel/sourcekite#9]
After I build sourcekite, most of the context information on moving the mouse cursor over elements does not work.
**Here is the output from trace when I mouse over the "print" command:**

[request] {
  key.request: source.request.cursorinfo,
  key.sourcefile: "/Users/daniel/Desktop/Xcode/Transformer/Sources/Transformer/main.swift",
  key.offset: 658,
  key.compilerargs: ["-target","x86_64-apple-macosx10.10","-swift-version","5","-enable-batch-mode","-index-store-path","/Users/daniel/Desktop/Xcode/Transformer/.build/x86_64-apple-macosx/debug/index/store","-sdk","/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk","-F","/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/Library/Frameworks","-Onone","-enable-testing","-g","-j16","-DSWIFT_PACKAGE","-DDEBUG","-module-cache-path","/Users/daniel/Desktop/Xcode/Transformer/.build/x86_64-apple-macosx/debug/ModuleCache","-parseable-output","-module-name","Transformer","-Onone","-Xcc","-I","-Xcc","/Users/daniel/Desktop/Xcode/Transformer/.build/x86_64-apple-macosx/debug","-I","/Users/daniel/Desktop/Xcode/Transformer/.build/x86_64-apple-macosx/debug","-Xcc","-F","-Xcc","/Users/daniel/Desktop/Xcode/Transformer/.build/x86_64-apple-macosx/debug","-F","/Users/daniel/Desktop/Xcode/Transformer/.build/x86_64-apple-macosx/debug","/Users/daniel/Desktop/Xcode/Transformer/Sources/Transformer/main.swift"],
  key.sourcetext: "import TensorFlow\n\nimport Python\n\nprint(Python.version)\n\nlet np = Python.import(\"numpy\")\nprint(np)\nlet zeros = np.ones([2, 3])\nprint(zeros)\n\nimport TensorFlow\n\nlet numpyArray = np.ones([4], dtype: np.float32)\nprint(\"Swift type:\", type(of: numpyArray))\nprint(\"Python type:\", Python.type(numpyArray))\nprint(numpyArray.shape)\n\n// Examples of converting `numpy.ndarray` to Swift types.\nlet array: [Float] = Array(numpy: numpyArray)!\nlet shapedArray = ShapedArray<Float>(numpy: numpyArray)!\nlet tensor = Tensor<Float>(numpy: numpyArray)!\n\n// Examples of converting Swift types to `numpy.ndarray`.\nprint(array.makeNumpyArray())\nprint(shapedArray.makeNumpyArray())\nprint(tensor.makeNumpyArray())\n\n// Examples with different dtypes.\nlet doubleArray: [Double] = Array(numpy: np.ones([3], dtype: np.float))!\nlet intTensor = Tensor<Int32>(numpy: np.ones([2, 3], dtype: np.int32))!\n\n\n"
}

[SourcekiteResponseHandler] 24
{
  "key.internal_diagnostic" : "Resolved to incomplete expression or statement."
}

**When I mouse over "Int32"**

[SourcekiteResponseHandler] 28
{
  "key.internal_diagnostic" : "Unable to resolve cursor info."
}

**On rare occasions, it does recognise the text, e.g. when I mouse over "array" the trace shows:**

[SourcekiteResponseHandler] 30
{
  "key.annotated_decl" : "<Declaration>let array: [<Type usr=\"s:Sf\">Float<\/Type>]<\/Declaration>",
  "key.filepath" : "\/Users\/daniel\/Desktop\/Xcode\/Transformer\/Sources\/Transformer\/main.swift",
  "key.fully_annotated_decl" : "<decl.var.global><syntaxtype.keyword>let<\/syntaxtype.keyword> <decl.name>array<\/decl.name>: <decl.var.type>[<ref.struct usr=\"s:Sf\">Float<\/ref.struct>]<\/decl.var.type><\/decl.var.global>",
  "key.kind" : "source.lang.swift.ref.var.global",
  "key.length" : 5,
  "key.name" : "array",
  "key.offset" : 386,
  "key.typename" : "[Float]",
  "key.typeusr" : "$sSaySfGD",
  "key.usr" : "s:11Transformer5arraySaySfGvp"
}

But most mouse over context info does not work.

**Comment by vknabel** [comment]
Hi @dbonner. Thanks for your bug report!

According to the logs you attached, you have a `TensorFlow` project, but your current Toolchain is set to Xccode's default. Please select the TensorFlow Toolchain (either using `xcode-select` or using Xcode as described in https://github.com/tensorflow/swift/blob/master/Usage.md#mac-only-xcode).

Then restart VS Code and run `swift build` once. Does it solve your issue?

**Comment by dbonner** [comment]
Hi @vknabel. Thanks for getting back to me.

I'm still getting the same problem.

My toolchain is set to tensorflow-LOCAL-2020-01-13-a according to Xcode-Preferences-Components-Toolchains, which is the way that is described in the link you sent me.  I don't know how to set the toolchain with xcode-select (I tried googling that).

The initial output of the log is:

Debugger listening on ws://127.0.0.1:6004/a6d1b8c7-deff-4e60-ade6-cf39bdbcd888
For help, see: https://nodejs.org/en/docs/inspector
[-->onInitialize ] isTracingOn=[true],
	skProtocolProcess=[/usr/local/bin/sourcekite],skProtocolProcessAsShellCmd=[false]
[-->onDidChangeConfiguration]
[-->onDidChangeConfiguration tracing:
	    swiftDiverBinPath=[/Library/Developer/Toolchains/swift-tensorflow-LOCAL-2020-01-13-a.xctoolchain/usr/bin/swift],
		shellPath=[/bin/sh]]
[sourcekite] ***sourcekite initializing with skProtocolProcess at [/usr/local/bin/sourcekite]
[-->SourcekiteResponseHandler constructor done]
[---onDidChangeContent]

Then when I mouse of the "print" command I get:

[request] {
  key.request: source.request.cursorinfo,
  key.sourcefile: "/Users/daniel/Desktop/Xcode/Transformer/Sources/Transformer/main.swift",
  key.offset: 679,
  key.compilerargs: ["-target","x86_64-apple-macosx10.10","-swift-version","5","-enable-batch-mode","-index-store-path","/Users/daniel/Desktop/Xcode/Transformer/.build/x86_64-apple-macosx/debug/index/store","-sdk","/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk","-F","/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/Library/Frameworks","-Onone","-enable-testing","-g","-j16","-DSWIFT_PACKAGE","-DDEBUG","-module-cache-path","/Users/daniel/Desktop/Xcode/Transformer/.build/x86_64-apple-macosx/debug/ModuleCache","-parseable-output","-module-name","Transformer","-Onone","-Xcc","-I","-Xcc","/Users/daniel/Desktop/Xcode/Transformer/.build/x86_64-apple-macosx/debug","-I","/Users/daniel/Desktop/Xcode/Transformer/.build/x86_64-apple-macosx/debug","-Xcc","-F","-Xcc","/Users/daniel/Desktop/Xcode/Transformer/.build/x86_64-apple-macosx/debug","-F","/Users/daniel/Desktop/Xcode/Transformer/.build/x86_64-apple-macosx/debug","/Users/daniel/Desktop/Xcode/Transformer/Sources/Transformer/main.swift"],
  key.sourcetext: "// Create version 3\n\nimport TensorFlow\n\nimport Python\n\nprint(Python.version)\n\nlet np = Python.import(\"numpy\")\nprint(np)\nlet zeros = np.ones([2, 3])\nprint(zeros)\n\nimport TensorFlow\n\nlet numpyArray = np.ones([4], dtype: np.float32)\nprint(\"Swift type:\", type(of: numpyArray))\nprint(\"Python type:\", Python.type(numpyArray))\nprint(numpyArray.shape)\n\n// Examples of converting `numpy.ndarray` to Swift types.\nlet array: [Float] = Array(numpy: numpyArray)!\nlet shapedArray = ShapedArray<Float>(numpy: numpyArray)!\nlet tensor = Tensor<Float>(numpy: numpyArray)!\n\n// Examples of converting Swift types to `numpy.ndarray`.\nprint(array.makeNumpyArray())\nprint(shapedArray.makeNumpyArray())\nprint(tensor.makeNumpyArray())\n\n// Examples with different dtypes.\nlet doubleArray: [Double] = Array(numpy: np.ones([3], dtype: np.float))!\nlet intTensor = Tensor<Int32>(numpy: np.ones([2, 3], dtype: np.int32))!\n\n\n"
}


[SourcekiteResponseHandler] 4
{
  "key.internal_diagnostic" : "Resolved to incomplete expression or statement."
}

**Comment by vknabel** [comment]
I just released [vscode-swift-development-environment@2.8.3](https://github.com/vknabel/vscode-swift-development-environment/releases/tag/2.8.3) which fixes a bug which ignored the toolchain path.

If you update and add the following config, does it improve autocompletion?

```json
{
    "sourcekit-lsp.toolchainPath": "/Library/Developer/Toolchains/swift-tensorflow-LOCAL-2020-01-13-a.xctoolchain"
}
```

**Comment by dbonner** [comment]
I figured it out.  I had installed gcc using homebrew.  I put a symbolic link (/usr/local/bin/gcc) that pointed to the gcc binary so that the command "gcc" ran gcc and not clang (the default macOS behaviour is to run clang when you issue the command "gcc").  I returned my mac to the default behaviour and built sourcekite.   It works properly now.
I will try your new version out still.

**Comment by vknabel** [comment]
Thanks for your explanation, didn't know about that!
